### PR TITLE
feat: add manual wrapper for v1beta2 read client

### PR DESCRIPTION
**Pull request by tswast**
We got a bit lucky in that the reader module doesn't create any proto objects, so it could be reused without modification from the "v1" endpoint. Maybe we should be defining these in a shared module that doesn't include the version information, though?

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:

- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

### CODE REVIEW

**Comment by tswast** [comment]
Kokoro failure:

```
    def test_snapshot(client, project_id, table_with_data_ref, bq_client):
>       before_new_data = types.Timestamp()
E       AttributeError: module 'google.cloud.bigquery_storage_v1beta2.types' has no attribute 'Timestamp'
```

I think there's a manual `synth.py` config for adding these types from the core protobuf. Will need to add before merging this PR.

**Comment by tswast** [comment]
Re: `AttributeError: module 'google.cloud.bigquery_storage_v1beta2.types' has no attribute 'Timestamp'`, the v1 API has a handwritten module https://github.com/googleapis/python-bigquery-storage/blob/master/google/cloud/bigquery_storage_v1/gapic_types.py which adds these.

@plamut Was this just for backwards compatibility? I imagine I could use the protobuf/proto-plus well-known type logic here instead.

**Comment by plamut** [comment]
@tswast Since I was not that familiar with this library, I _think_ I included these generated types to avoid import errors when transitioning to the microgenerator, but I didn't explore if all of these types are still needed.

The old proto types probably could be replaced with their `proto-plus` counterparts, but if taking that route, we must check that it doesn't introduce a performance regression. The change was very significant in PubSub because the `proto-plus` attribute access is slower and we had to circumvent it internally in order to retain most of the performance of the 1.x client.

**Comment by tswast** [comment]
This is ready for review. I used some parameterized test fixtures to keep from duplicating code in the system tests. Next, I'll start looking more closely at what needs to be done for the write client.

**Review by shollyman — APPROVED** [review]

**Pull request merged**
