### PR TITLE
Fix: Add response object to any append rows requests exception

### LINKED ISSUE #836: No way to observe the AppendRowsResponse row_errors
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

Please run down the following list and make sure you've tried the usual "quick fixes":

  - Search the issues already opened: https://github.com/googleapis/python-bigquery-storage/issues
  - Search StackOverflow: https://stackoverflow.com/questions/tagged/google-cloud-platform+python

If you are still having issues, please be sure to include as much information as possible:

#### Environment details

  - OS type and version:
  - Python version: `python --version`
  - pip version: `pip --version`
  - `google-cloud-bigquery-storage` version: `pip show google-cloud-bigquery-storage`

```
$ pip show google-cloud-bigquery-storage
Name: google-cloud-bigquery-storage
Version: 2.26.0
Summary: Google Cloud Bigquery Storage API client library
Home-page: https://github.com/googleapis/python-bigquery-storage
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Location: /Users/film42/.pyenv/versions/3.10.9/envs/banzai-sept-2/lib/python3.10/site-packages
Requires: google-api-core, google-auth, proto-plus, protobuf
Required-by: 
```

#### Steps to reproduce

1. Use a STRING protobuf field to append a row with a DATETIME bigquery column type using the value `'2024-10-11T00:17:35.479490+00:00'`.

Please see previous issue https://github.com/googleapis/python-bigquery-storage/issues/717 where @bhavitsharma ran into the same issue as I did.

#### Code example

```python

datetime_string = dt.datetime.now(dt.timezone.utc).isoformat()

p = MyProto()
p.created_at = datetime_string

# perform a normal append ...

try:
  future = append_rows_stream.send(request)
  future.result()
except InvalidArgument as e:
  pass
  # How are you supposed to get the AppendRowsResponse object?
```

Docs here say that errors must be read from the response which includes an index, msg, and error type for each row. https://cloud.google.com/bigquery/docs/reference/storage/rpc/google.cloud.bigquery.storage.v1#google.cloud.bigquery.storage.v1.AppendRowsResponse . But, there is no way to get access to the underlying response because on error this lib capture the code and message and throws away the rest:

https://github.com/googleapis/python-bigquery-storage/blob/4c871787139c048099c80b5d8700537fc0824e2c/google/cloud/bigquery_storage_v1/writer.py#L285-L292

If you crack open the source code of this lib and modify it to print the `response.row_errors` you get:

```python
print(response.row_errors[499])

index: 499
code: FIELDS_ERROR
message: "Invalid date time value \'2024-10-11T00:17:35.479490+00:00\' on field \'MyProto.created_at\'"
```

#### Stack trace

Without access to the response to inspect each row, this is the only thing you see:

`400 Errors found while processing rows. Please refer to the row_errors field for details. The list may not be complete because of the size limitations. Entity: projects/my_project/datasets/my_dataset/tables/my_table/streams/my_stream_id`

In other words... nothing helpful.

I think it would be great if we _could_ have something like:

```python
try:
  append_rows_stream.send(request).result()
except InvalidArgument as e:
  # Provide access to the response on the InvalidArgument error...
  print(e.response.row_errors[499].message)
```

OR

```python
try:
  future = append_rows_stream.send(request)
  future.result()
except InvalidArgument as e:
  # Allow this custom AppendRowsFuture object to retain access to the underlying response
  print(future.response().row_errors[499].message)
```

### PR DESCRIPTION
**Pull request by film42**
Should an AppendRowsRequest fail, you need to inspect the response to see what went wrong. Currently this lib only raises an exception with the code and message, throwing the actual response away. This patch adds the response to any exception raise. This is fine because the base grpc error has a response kwarg that this lib wasn't using.

Now you can catch the error and call `e.response.row_errors` to see the underlying row errors.

Fixes: https://github.com/googleapis/python-bigquery-storage/issues/836

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #836 🦕

NOTE: I didn't have time to set up the system test env to verify the test I added passes so I'm just going to test it in CI here on github. If it doesn't work we can probably just delete it.

### CODE REVIEW

**Review by yirutang — APPROVED** [review]

**Comment by bhavitsharma** [comment]
any way to prioritize this PR? it's very very troublesome to debug an errors with write APIs without modifying the source code. @yirutang @agrawal-siddharth

**Comment by yirutang** [comment]
> any way to prioritize this PR? it's very very troublesome to debug any errors with write APIs without modifying the source code. @yirutang @agrawal-siddharth

Sorry about this! The release process is experiencing some blockers and I am looping in DevRel experts to answer this question. @leahecole

**Comment by leahecole** [comment]
Hi @yirutang and @bhavitsharma - this PR is still on our radar - as Yiru said, the entire release process has an issue right now that we all are eagerly anticipating being resolved. The fix is being rolled out incrementally and should be in this repo soon. I am making sure that @yirutang is cc'd on the appropriate bug for updates and I do check on this process every day and reach out to the engineers working on the fix.

**Comment by bhavitsharma** [comment]
Thank you for the update!

**Review by parthea — COMMENTED** [review]
Please see the following failure which appears when using pre-release version of protobuf

```
=================================== FAILURES ===================================
_____________ test_append_rows_with_invalid_stream_name_fails_fast _____________

bqstorage_write_client = 

    def test_append_rows_with_invalid_stream_name_fails_fast(bqstorage_write_client):
        bad_request = gapic_types.AppendRowsRequest()
        bad_request.write_stream = "this-is-an-invalid-stream-resource-path"
    
        with pytest.raises(exceptions.GoogleAPICallError) as excinfo:
            bqstorage_write_client.append_rows(bad_request)
    
>       assert isinstance(excinfo.value.response, gapic_types.AppendRowsResponse)
E       assert False
E        +  where False = isinstance(<_MultiThreadedRendezvous of RPC that terminated with:\n	status = StatusCode.UNKNOWN\n	details = "Exception iterating requests!"\n	debug_error_string = "None"\n>, )
E        +    where <_MultiThreadedRendezvous of RPC that terminated with:\n	status = StatusCode.UNKNOWN\n	details = "Exception iterating requests!"\n	debug_error_string = "None"\n> = Unknown('Exception iterating requests!').response
E        +      where Unknown('Exception iterating requests!') = .value
E        +    and    = gapic_types.AppendRowsResponse
```

```
nox > python -c 'import google.protobuf; print(google.protobuf.__version__)'
5.29.0rc2
```

**Comment by parthea** [comment]
Adding `do not merge` until `Kokoro Prerelease Dependencies ` is fixed. See https://github.com/googleapis/python-bigquery-storage/pull/838#pullrequestreview-2395931452

**Comment by Linchin** [comment]
The system failed because in the fail-fast test, the response was never created. I added a new system test with an invalid request, which should work.

**Review by chalmerlowe — APPROVED** [review]
@film42 Thanks for submitting this PR. It is much appreciated.
@Linchin Thanks for helping get it across the finish line.

LGTM, Approved.

**Pull request merged**
