### PR TITLE
chore: migrate default branch to main

### LINKED ISSUE #280: Migrate from master to main branch
As part of the umbrella issue googleapis/google-cloud-python#10579, we need to switch the default branch from `master` to `main`. Also, all occurrences of `master` should be renamed to `main` (except in cases where URLs could be broken, because the migration has not happened yet).

### PR DESCRIPTION
**Pull request by plamut**
Fixes #280.

### CODE REVIEW

**Comment by plamut** [comment]
There are still some references to `master` left, but all of them in URLs to repos that have not migrated yet. I left those out for now to not cause any unnecessary 404 errors for the end users.

**Review by tseaver — COMMENTED** [review]
I'm surprised you didn't have to add replacments to `owlbot.py` to make these changes stick.  Is the bot not configured to run on PRs in this repository?

**Comment by plamut** [comment]
I ran [this script](https://github.com/googleapis/google-cloud-python/pull/10581/files), but apparently it did not find and "master" patterns and thus didn't make any replacements?

(searching for "master" in the codebase did not yield anything apart from a few URLs to repos that have not done the migration yet)

**Comment by tseaver** [comment]
@plamut I don't see that the `Owlbot Post Processor` check is configured here:  if it ran, I think it would revert at least some of your changes here to templated files.  @parthea can you investigate?

**Comment by plamut** [comment]
Putting this on hold as well.

**Comment by parthea** [comment]
I've added the `owlbot:run` label which should trigger owlbot to run. It should have been triggered automatically but I have noticed that there is the odd time that I need to add the label to get it to run.

**Comment by parthea** [comment]
Hi @plamut , Please let me know if you have any questions.

**Pull request closed without merging**
