### PR TITLE
feat: add client side lib id with lib version

### PR DESCRIPTION
**Pull request by yirutang**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Fixes #<issue_number_goes_here> 🦕

### CODE REVIEW

**Comment by Linchin** [comment]
Thank you @yirutang, just so I understand the PR better, could you let me know if this PR is only changing the generated code? Also, I see a lot of changes with import formats, but where is client side lib id added?

**Comment by yirutang** [comment]
> Thank you @yirutang, just so I understand the PR better, could you let me know if this PR is only changing the generated code? Also, I see a lot of changes with import formats, but where is client side lib id added?

Yes, there is a few lines of additions here, in py_writer. I ran the suggested `nox -r -s format` and it did all these sortings for me. Maybe it is not needed? Let me revert the changes back.

**Review by Linchin — APPROVED** [review]
Thank you @yirutang! Question unrelated to approval: where on the backend will the version data be available?

**Comment by yirutang** [comment]
> Thank you @yirutang! Question unrelated to approval: where on the backend will the version data be available?

It will be BQ backend's general logging (helixdata2), which is a project in BQ itself.

**Pull request merged**
