### PR TITLE
chore: remove hack for installing extras from synth.py

### PR DESCRIPTION
**Pull request by tswast**
This uses the templates added in
https://github.com/googleapis/synthtool/pull/906

Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [ ] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [ ] Ensure the tests and linter pass
- [ ] Code coverage does not decrease (if any source code was changed)
- [ ] Appropriate docs were updated (if necessary)

Closes https://github.com/googleapis/python-bigquery-storage/pull/115

### CODE REVIEW

**Comment by tswast** [comment]
Ready for review.

**Review by plamut — APPROVED** [review]
This looks good IMO. :+1: 

And thanks for adding that synthtool improvement in the first place.

**Review by plamut — CHANGES_REQUESTED** [review]
I just realized `pyarrow==3.0.0` was released yesterday, meaning that conditionally installing it is not needed anymore (well, at least until we start thinking Python 3.10 support :laughing: ).

Let's remove that logic then.

**Comment by tswast** [comment]
@plamut removed Python 3.9 exception and re-ran `python -m synthtool` with latest templates.

**Review by plamut — APPROVED** [review]
LGTM

**Pull request merged**
