### PR TITLE
docs: add samples from bigquery_storage/to_dataframe

### LINKED ISSUE #51: Add bigquery_storage/to_dataframe samples from the samples repo
This is a prerequisite for migrating the library to microgenerator.

### PR DESCRIPTION
**Pull request by plamut**
Samples from https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/bigquery_storage/to_dataframe

---
> **IMPORTANT:** When merging, use the **rebase and merge** option to preserve the samples commit history!
---

Closes #51.

### CODE REVIEW

**Comment by plamut** [comment]
The tests fail, because they expect the results to contain Python objects, but the actual results are Pyarrow objects, e.g. `123` vs. `<pyarrow.Int64Scalar: 123>`.

@shollyman Is this actually expected behavior and pyarrow values need to be converted to Python objects explicitly, or should `ReadRowsStream.rows()` convert the results automatically before handing them to the user?

**Comment by busunkim96** [comment]
It looks like the regular Kokoro job is also running the sample tests https://github.com/googleapis/python-bigquery-storage/blob/master/noxfile.py#L135

There seems to only be one existing [sample](https://github.com/googleapis/python-bigquery-storage/tree/master/samples) in this repo. Here is what I suggest:
* move the quickstart into `dataframe` or some other directory nested under `samples`
* re-run synthtool
* delete the `samples` nox session in the library's main noxfile.py
* merge PR
* follow with a docs update internally

**Comment by plamut** [comment]
@busunkim96 Done. I had to tweak a few things (e.g. dependencies), but now the samples tests pass locally - both the migrated `to_dataframe/` and the existing `quickstart` which was moved to its own subdirectory.

**Review by busunkim96 — APPROVED** [review]

**Comment by plamut** [comment]
@busunkim96 Please also appease the CLA bot on my behalf, thanks!

**Pull request merged**
