### PR TITLE
feat: add support for proto3 optional tag

### LINKED ISSUE #726: The write stream is not compatible with proto3
#### Environment details

  - OS type and version: MacOS 14.2
  - Python version: 3.11
  - pip version: 23.2.1
  - `google-cloud-bigquery-storage` version: 2.24.0

#### Steps to reproduce

  1. When attempting to open a new write stream using proto3 schema, a server-side error will be triggered.

#### Code example

```python
write_client = BigQueryWriteClient()
parent = write_client.table_path(project_id, dataset_id, table_id)
write_stream = types.WriteStream()

write_stream.type_ = types.WriteStream.Type.PENDING
write_stream = write_client.create_write_stream(
    parent=parent, write_stream=write_stream
)
stream_name = write_stream.name

# Create a template with fields needed for the first request.
request_template = types.AppendRowsRequest()

# The initial request must contain the stream name.
request_template.write_stream = stream_name

# So that BigQuery knows how to parse the serialized_rows, generate a
# protocol buffer representation of your message descriptor.
proto_schema = types.ProtoSchema()
proto_descriptor = descriptor_pb2.DescriptorProto()
# The `proto` is a proto with proto3 features enabled
proto.DESCRIPTOR.CopyToProto(
    proto_descriptor,
)

proto_schema.proto_descriptor = proto_descriptor
proto_data = types.AppendRowsRequest.ProtoData()
proto_data.writer_schema = proto_schema
request_template.proto_rows = proto_data

append_rows_stream = writer.AppendRowsStream(
    write_client,
    request_template,
)
```

#### Stack trace
```
google.api_core.exceptions.InvalidArgument: 400 Invalid proto schema: BqMessage.proto: customer_client_pb3.customer_client_id: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_id
BqMessage.proto: customer_client_pb3.customer_client_level: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_level
BqMessage.proto: customer_client_pb3.customer_client_manager: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_manager
BqMessage.proto: customer_client_pb3.customer_client_status: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_status Entity: [****] [detail: "INVALID_ARGUMENT: Invalid proto schema: BqMessage.proto: customer_client_pb3.customer_client_id: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_id\nBqMessage.proto: customer_client_pb3.customer_client_level: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_level\nBqMessage.proto: customer_client_pb3.customer_client_manager: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_manager\nBqMessage.proto: customer_client_pb3.customer_client_status: The [proto3_optional=true] option may only be set on proto3fields, not customer_client_pb3.customer_client_status [type.googleapis.com/util.MessageSetPayload=\'[cloud.helix.vortex.VortexStatus] { error_code: INVALID_ARGUMENT component: FRONTEND is_public_error: true }\']"
```

### PR DESCRIPTION
**Pull request by Dumeng**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-bigquery-storage/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #726 🦕 

The solution is similar to the fix in the Java client SDK. 
https://github.com/googleapis/java-bigquerystorage/pull/2295

### CODE REVIEW

**Comment by Linchin** [comment]
Hi @Dumeng, thank you so much for making the contribution! Being compatible with proto3 would be very helpful.

I have a few questions/suggestions:
1. Maybe we can add unit tests and system tests to verify that proto3 is indeed supported
2. Should we consider adding the same treatment for read clients too?

Please let us know if you need any help, we are more than glad to work with you :)

**Comment by Dumeng** [comment]
Hi @Linchin , Thanks for your reply.
1. The error is coming from the server-side, so the unit test may not be able to verify the fix. I'm not familiar with the system test framework this project is using, I need some research.
2. The `ReadRowsStream` seems does not need a proto description in its request. The proto description is required and causes the error in the `AppendRowsStream`.

**Comment by Dumeng** [comment]
Hi @Linchin , Thanks for your reply.
1. The error is coming from the server-side, so the unit test may not be able to verify the fix. I'm not familiar with the system test framework this project is using, I need some research.
2. The `ReadRowsStream` seems does not need a proto description in its request. The proto description is required and causes the error in the `AppendRowsStream`.

**Comment by Linchin** [comment]
Thanks for adding the system test! I think the system test has failed, and you can see the logs [here](https://btx-internal.corp.google.com/invocations/4c768a9a-e5e2-4691-ba06-e500e8d38bff/targets/cloud-devrel%2Fclient-libraries%2Fpython%2Fgoogleapis%2Fpython-bigquery-storage%2Fpresubmit%2Fpresubmit;config=default/log). We also need to run the linter to pass the lint test. 

Also, as you can see we only have tests for v1. Since v1beta1 is going to be deprecated soon, and we don't have tests to verify that it works, I think it's a better idea to restrain our change here to v1.

**Review by Linchin — APPROVED** [review]
Thank you for adding support for proto3!

**Pull request merged**
